<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        $countries = [
            ['id' => 1 ,'name' => "Afghanistan"],
            ['id' => 2 ,'name' => "Albania"],
            ['id' => 3 ,'name' => "Algeria"],
            ['id' => 4 ,'name' => "American Samoa"],
            ['id' => 5 ,'name' => "Andorra"],
            ['id' => 6 ,'name' => "Angola"],
            ['id' => 7 ,'name' => "Anguilla"],
            ['id' => 8 ,'name' => "Antarctica"],
            ['id' => 9 ,'name' => "Antigua And Barbuda"],
            ['id' => 10,'name' => "Argentina"],
            ['id' => 11,'name' => "Armenia"],
            ['id' => 12,'name' => "Aruba"],
            ['id' => 13,'name' => "Australia"],
            ['id' => 14,'name' => "Austria"],
            ['id' => 15,'name' => "Azerbaijan"],
            ['id' => 16,'name' => "Bahamas The"],
            ['id' => 17,'name' => "Bahrain"],
            ['id' => 18,'name' => "Bangladesh"],
            ['id' => 19,'name' => "Barbados"],
            ['id' => 20,'name' => "Belarus"],
            ['id' => 21,'name' => "Belgium"],
            ['id' => 22,'name' => "Belize"],
            ['id' => 23,'name' => "Benin"],
            ['id' => 24,'name' => "Bermuda"],
            ['id' => 25,'name' => "Bhutan"],
            ['id' => 26,'name' => "Bolivia"],
            ['id' => 27,'name' => "Bosnia and Herzegovina"],
            ['id' => 28,'name' => "Botswana"],
            ['id' => 29,'name' => "Bouvet Island"],
            ['id' => 30,'name' => "Brazil"],
            ['id' => 31,'name' => "British Indian Ocean Territory"],
            ['id' => 32,'name' => "Brunei"],
            ['id' => 33,'name' => "Bulgaria"],
            ['id' => 34,'name' => "Burkina Faso"],
            ['id' => 35,'name' => "Burundi"],
            ['id' => 36,'name' => "Cambodia"],
            ['id' => 37,'name' => "Cameroon"],
            ['id' => 38,'name' => "Canada"],
            ['id' => 39,'name' => "Cape Verde"],
            ['id' => 40,'name' => "Cayman Islands"],
            ['id' => 41,'name' => "Central African Republic"],
            ['id' => 42,'name' => "Chad"],
            ['id' => 43,'name' => "Chile"],
            ['id' => 44,'name' => "China"],
            ['id' => 45,'name' => "Christmas Island"],
            ['id' => 46,'name' => "Cocos (Keeling) Islands"],
            ['id' => 47,'name' => "Colombia"],
            ['id' => 48,'name' => "Comoros"],
            ['id' => 49,'name' => "Congo"],
            ['id' => 50,'name' => "Congo The Democratic Republic Of The"],
            ['id' => 51,'name' => "Cook Islands"],
            ['id' => 52,'name' => "Costa Rica"],
            ['id' => 53,'name' => "Cote D Ivoire (Ivory Coast)"],
            ['id' => 54,'name' => "Croatia (Hrvatska)"],
            ['id' => 55,'name' => "Cuba"],
            ['id' => 56,'name' => "Cyprus"],
            ['id' => 57,'name' => "Czech Republic"],
            ['id' => 58,'name' => "Denmark"],
            ['id' => 59,'name' => "Djibouti"],
            ['id' => 60,'name' => "Dominica"],
            ['id' => 61,'name' => "Dominican Republic"],
            ['id' => 62,'name' => "East Timor"],
            ['id' => 63,'name' => "Ecuador"],
            ['id' => 64,'name' => "Egypt"],
            ['id' => 65,'name' => "El Salvador"],
            ['id' => 66,'name' => "Equatorial Guinea"],
            ['id' => 67,'name' => "Eritrea"],
            ['id' => 68,'name' => "Estonia"],
            ['id' => 69,'name' => "Ethiopia"],
            ['id' => 70,'name' => "External Territories of Australia"],
            ['id' => 71,'name' => "Falkland Islands"],
            ['id' => 72,'name' => "Faroe Islands"],
            ['id' => 73,'name' => "Fiji Islands"],
            ['id' => 74,'name' => "Finland"],
            ['id' => 75,'name' => "France"],
            ['id' => 76,'name' => "French Guiana"],
            ['id' => 77,'name' => "French Polynesia"],
            ['id' => 78,'name' => "French Southern Territories"],
            ['id' => 79,'name' => "Gabon"],
            ['id' => 80,'name' => "Gambia The"],
            ['id' => 81,'name' => "Georgia"],
            ['id' => 82,'name' => "Germany"],
            ['id' => 83,'name' => "Ghana"],
            ['id' => 84,'name' => "Gibraltar"],
            ['id' => 85,'name' => "Greece"],
            ['id' => 86,'name' => "Greenland"],
            ['id' => 87,'name' => "Grenada"],
            ['id' => 88,'name' => "Guadeloupe"],
            ['id' => 89,'name' => "Guam"],
            ['id' => 90,'name' => "Guatemala"],
            ['id' => 91,'name' => "Guernsey and Alderney"],
            ['id' => 92,'name' => "Guinea"],
            ['id' => 93,'name' => "Guinea-Bissau"],
            ['id' => 94,'name' => "Guyana"],
            ['id' => 95,'name' => "Haiti"],
            ['id' => 96,'name' => "Heard and McDonald Islands"],
            ['id' => 97,'name' => "Honduras"],
            ['id' => 98,'name' => "Hong Kong S.A.R."],
            ['id' => 99,'name' => "Hungary"],
            ['id' => 100,'name' => "Iceland"],
            ['id' => 101,'name' => "India"],
            ['id' => 102,'name' => "Indonesia"],
            ['id' => 103,'name' => "Iran"],
            ['id' => 104,'name' => "Iraq"],
            ['id' => 105,'name' => "Ireland"],
            ['id' => 106,'name' => "Israel"],
            ['id' => 107,'name' => "Italy"],
            ['id' => 108,'name' => "Jamaica"],
            ['id' => 109,'name' => "Japan"],
            ['id' => 110,'name' => "Jersey"],
            ['id' => 111,'name' => "Jordan"],
            ['id' => 112,'name' => "Kazakhstan"],
            ['id' => 113,'name' => "Kenya"],
            ['id' => 114,'name' => "Kiribati"],
            ['id' => 115,'name' => "Korea North"],
            ['id' => 116,'name' => "Korea South"],
            ['id' => 117,'name' => "Kuwait"],
            ['id' => 118,'name' => "Kyrgyzstan"],
            ['id' => 119,'name' => "Laos"],
            ['id' => 120,'name' => "Latvia"],
            ['id' => 121,'name' => "Lebanon"],
            ['id' => 122,'name' => "Lesotho"],
            ['id' => 123,'name' => "Liberia"],
            ['id' => 124,'name' => "Libya"],
            ['id' => 125,'name' => "Liechtenstein"],
            ['id' => 126,'name' => "Lithuania"],
            ['id' => 127,'name' => "Luxembourg"],
            ['id' => 128,'name' => "Macau S.A.R."],
            ['id' => 129,'name' => "Macedonia"],
            ['id' => 130,'name' => "Madagascar"],
            ['id' => 131,'name' => "Malawi"],
            ['id' => 132,'name' => "Malaysia"],
            ['id' => 133,'name' => "Maldives"],
            ['id' => 134,'name' => "Mali"],
            ['id' => 135,'name' => "Malta"],
            ['id' => 136,'name' => "Man (Isle of)"],
            ['id' => 137,'name' => "Marshall Islands"],
            ['id' => 138,'name' => "Martinique"],
            ['id' => 139,'name' => "Mauritania"],
            ['id' => 140,'name' => "Mauritius"],
            ['id' => 141,'name' => "Mayotte"],
            ['id' => 142,'name' => "Mexico"],
            ['id' => 143,'name' => "Micronesia"],
            ['id' => 144,'name' => "Moldova"],
            ['id' => 145,'name' => "Monaco"],
            ['id' => 146,'name' => "Mongolia"],
            ['id' => 147,'name' => "Montserrat"],
            ['id' => 148,'name' => "Morocco"],
            ['id' => 149,'name' => "Mozambique"],
            ['id' => 150,'name' => "Myanmar"],
            ['id' => 151,'name' => "Namibia"],
            ['id' => 152,'name' => "Nauru"],
            ['id' => 153,'name' => "Nepal"],
            ['id' => 154,'name' => "Netherlands Antilles"],
            ['id' => 155,'name' => "Netherlands The"],
            ['id' => 156,'name' => "New Caledonia"],
            ['id' => 157,'name' => "New Zealand"],
            ['id' => 158,'name' => "Nicaragua"],
            ['id' => 159,'name' => "Niger"],
            ['id' => 160,'name' => "Nigeria"],
            ['id' => 161,'name' => "Niue"],
            ['id' => 162,'name' => "Norfolk Island"],
            ['id' => 163,'name' => "Northern Mariana Islands"],
            ['id' => 164,'name' => "Norway"],
            ['id' => 165,'name' => "Oman"],
            ['id' => 166,'name' => "Pakistan"],
            ['id' => 167,'name' => "Palau"],
            ['id' => 168,'name' => "Palestinian Territory Occupied"],
            ['id' => 169,'name' => "Panama"],
            ['id' => 170,'name' => "Papua new Guinea"],
            ['id' => 171,'name' => "Paraguay"],
            ['id' => 172,'name' => "Peru"],
            ['id' => 173,'name' => "Philippines"],
            ['id' => 174,'name' => "Pitcairn Island"],
            ['id' => 175,'name' => "Poland"],
            ['id' => 176,'name' => "Portugal"],
            ['id' => 177,'name' => "Puerto Rico"],
            ['id' => 178,'name' => "Qatar"],
            ['id' => 179,'name' => "Reunion"],
            ['id' => 180,'name' => "Romania"],
            ['id' => 181,'name' => "Russia"],
            ['id' => 182,'name' => "Rwanda"],
            ['id' => 183,'name' => "Saint Helena"],
            ['id' => 184,'name' => "Saint Kitts And Nevis"],
            ['id' => 185,'name' => "Saint Lucia"],
            ['id' => 186,'name' => "Saint Pierre and Miquelon"],
            ['id' => 187,'name' => "Saint Vincent And The Grenadines"],
            ['id' => 188,'name' => "Samoa"],
            ['id' => 189,'name' => "San Marino"],
            ['id' => 190,'name' => "Sao Tome and Principe"],
            ['id' => 191,'name' => "Saudi Arabia"],
            ['id' => 192,'name' => "Senegal"],
            ['id' => 193,'name' => "Serbia"],
            ['id' => 194,'name' => "Seychelles"],
            ['id' => 195,'name' => "Sierra Leone"],
            ['id' => 196,'name' => "Singapore"],
            ['id' => 197,'name' => "Slovakia"],
            ['id' => 198,'name' => "Slovenia"],
            ['id' => 199,'name' => "Smaller Territories of the UK"],
            ['id' => 200,'name' => "Solomon Islands"],
            ['id' => 201,'name' => "Somalia"],
            ['id' => 202,'name' => "South Africa"],
            ['id' => 203,'name' => "South Georgia"],
            ['id' => 204,'name' => "South Sudan"],
            ['id' => 205,'name' => "Spain"],
            ['id' => 206,'name' => "Sri Lanka"],
            ['id' => 207,'name' => "Sudan"],
            ['id' => 208,'name' => "Suriname"],
            ['id' => 209,'name' => "Svalbard And Jan Mayen Islands"],
            ['id' => 210,'name' => "Swaziland"],
            ['id' => 211,'name' => "Sweden"],
            ['id' => 212,'name' => "Switzerland"],
            ['id' => 213,'name' => "Syria"],
            ['id' => 214,'name' => "Taiwan"],
            ['id' => 215,'name' => "Tajikistan"],
            ['id' => 216,'name' => "Tanzania"],
            ['id' => 217,'name' => "Thailand"],
            ['id' => 218,'name' => "Togo"],
            ['id' => 219,'name' => "Tokelau"],
            ['id' => 220,'name' => "Tonga"],
            ['id' => 221,'name' => "Trinidad And Tobago"],
            ['id' => 222,'name' => "Tunisia"],
            ['id' => 223,'name' => "Turkey"],
            ['id' => 224,'name' => "Turkmenistan"],
            ['id' => 225,'name' => "Turks And Caicos Islands"],
            ['id' => 226,'name' => "Tuvalu"],
            ['id' => 227,'name' => "Uganda"],
            ['id' => 228,'name' => "Ukraine"],
            ['id' => 229,'name' => "United Arab Emirates"],
            ['id' => 230,'name' => "United Kingdom"],
            ['id' => 231,'name' => "United States"],
            ['id' => 232,'name' => "United States Minor Outlying Islands"],
            ['id' => 233,'name' => "Uruguay"],
            ['id' => 234,'name' => "Uzbekistan"],
            ['id' => 235,'name' => "Vanuatu"],
            ['id' => 236,'name' => "Vatican City State (Holy See)"],
            ['id' => 237,'name' => "Venezuela"],
            ['id' => 238,'name' => "Vietnam"],
            ['id' => 239,'name' => "Virgin Islands (British)"],
            ['id' => 240,'name' => "Virgin Islands (US)"],
            ['id' => 241,'name' => "Wallis And Futuna Islands"],
            ['id' => 242,'name' => "Western Sahara"],
            ['id' => 243,'name' => "Yemen"],
            ['id' => 244,'name' => "Yugoslavia"],
            ['id' => 245,'name' => "Zambia"],
            ['id' => 246,'name' => "Zimbabwe"],
        ];
            DB::table('countries')->insert($countries);
    }
}
